const cfg=window.GITE_CONFIG;const navBtn=document.querySelector('.nav-toggle'),nav=document.querySelector('.main-nav');navBtn.addEventListener('click',()=>{nav.classList.toggle('open');navBtn.setAttribute('aria-expanded',nav.classList.contains('open'))});document.querySelectorAll('.main-nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const phone=document.getElementById('phoneLink');phone.textContent=cfg.phone;phone.href=`tel:${cfg.phoneHref}`;document.getElementById('calendarUpdated').textContent=cfg.lastCalendarUpdate;
function iso(d){return d.toISOString().slice(0,10)}function inRange(date,r){return date>=new Date(r.from+'T00:00:00')&&date<new Date(r.to+'T00:00:00')}function isBooked(d){return cfg.bookedRanges.some(r=>inRange(d,r))}function rateFor(d){return cfg.rates.find(r=>inRange(d,r))}
let view=new Date();view=new Date(view.getFullYear(),view.getMonth(),1);const months=['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'];
function renderCalendar(){const cal=document.getElementById('calendar');cal.innerHTML='';document.getElementById('calendarTitle').textContent=`${months[view.getMonth()]} ${view.getFullYear()}`;const first=(view.getDay()+6)%7;const start=new Date(view.getFullYear(),view.getMonth(),1-first);const today=new Date();today.setHours(0,0,0,0);for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const el=document.createElement('div');el.className='day';if(d.getMonth()!==view.getMonth())el.classList.add('other');if(isBooked(d))el.classList.add('booked');if(d.getTime()===today.getTime())el.classList.add('today');el.textContent=d.getDate();const rate=rateFor(d);el.title=rate?`${rate.price} € / nuit`:isBooked(d)?'Réservé':'Disponible – tarif à confirmer';cal.appendChild(el)}}renderCalendar();document.getElementById('prevMonth').onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()-1,1);renderCalendar()};document.getElementById('nextMonth').onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()+1,1);renderCalendar()};
function nights(a,b){return Math.round((b-a)/86400000)}function datesOverlap(a,b){for(const r of cfg.bookedRanges){const rf=new Date(r.from+'T00:00:00'),rt=new Date(r.to+'T00:00:00');if(a<rt&&b>rf)return true}return false}
function priceEstimate(a,b){let total=0,complete=true;for(let d=new Date(a);d<b;d.setDate(d.getDate()+1)){const r=rateFor(d);if(!r){complete=false;continue}total+=Number(r.price)}return complete?total:null}
document.getElementById('checkDates').onclick=()=>{const res=document.getElementById('availabilityResult'),av=document.getElementById('arrival').value,de=document.getElementById('departure').value;if(!av||!de){res.textContent='Choisissez une date d’arrivée et une date de départ.';return}const a=new Date(av+'T00:00:00'),b=new Date(de+'T00:00:00'),n=nights(a,b);if(n<cfg.minNights){res.textContent=`Le séjour minimum est de ${cfg.minNights} nuits.`;return}if(datesOverlap(a,b)){res.textContent='Certaines dates sont déjà réservées. Choisissez une autre période.';return}const p=priceEstimate(a,b);res.textContent=p!==null?`Période disponible : ${n} nuits, estimation ${p} € hors options.`:`Période a priori disponible : ${n} nuits. Le tarif sera confirmé avec votre demande.`;document.querySelector('[name="arrival"]').value=av;document.querySelector('[name="departure"]').value=de};
const form=document.getElementById('requestForm');form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);const msg=`Demande de réservation – Gîte Un air de Toscane\n\nNom : ${d.get('name')}\nTéléphone : ${d.get('phone')||'-'}\nE-mail : ${d.get('email')}\nArrivée : ${d.get('arrival')}\nDépart : ${d.get('departure')}\nAdultes : ${d.get('adults')}\nEnfants : ${d.get('children')}\n\nMessage : ${d.get('message')||'-'}`;if(cfg.email){window.location.href=`mailto:${cfg.email}?subject=${encodeURIComponent('Demande de réservation – Un air de Toscane')}&body=${encodeURIComponent(msg)}`}else{navigator.clipboard?.writeText(msg);const s=document.getElementById('formStatus');s.textContent='Demande préparée et copiée. L’adresse e-mail de réservation sera branchée dès que vous me la donnerez.'}});
const todayIso=iso(new Date());document.querySelectorAll('input[type="date"]').forEach(i=>i.min=todayIso);
